-- Script generated by Redgate Compare v1.7.1.7682

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating tablefunc...';END$$;
CREATE EXTENSION tablefunc WITH SCHEMA public VERSION '1.0';


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.social_networks...';END$$;
CREATE TABLE public.social_networks (
    social_network_id integer NOT NULL,
    name text NOT NULL,
    required boolean DEFAULT false
);
ALTER TABLE public.social_networks ADD CONSTRAINT social_networks_pkey PRIMARY KEY (social_network_id);


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.actor_social...';END$$;
CREATE TABLE public.actor_social (
    actor_id integer,
    social_network_id integer,
    handle text NOT NULL
);


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.idx_social_network_id...';END$$;
CREATE INDEX idx_social_network_id ON public.actor_social USING btree (social_network_id);


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.idx_actor_id...';END$$;
CREATE INDEX idx_actor_id ON public.actor_social USING btree (actor_id);


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.actor_social.actor_social_social_network_id_fkey...';END$$;
ALTER TABLE public.actor_social ADD CONSTRAINT actor_social_social_network_id_fkey FOREIGN KEY (social_network_id) REFERENCES public.social_networks (social_network_id) ON DELETE CASCADE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.actor_social.actor_social_actor_id_fkey...';END$$;
ALTER TABLE public.actor_social ADD CONSTRAINT actor_social_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.actor (actor_id) ON DELETE CASCADE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.social_networks_social_network_id_seq...';END$$;
CREATE SEQUENCE public.social_networks_social_network_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE
OWNED BY public.social_networks.social_network_id;
SET check_function_bodies = true;
