-- Script generated by Redgate Compare v1.7.1.7682

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating pg_trgm...';END$$;
CREATE EXTENSION pg_trgm WITH SCHEMA public VERSION '1.6';
SET check_function_bodies = true;
