-- Script generated by Redgate Compare v1.11.2.9453

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.ix_abc_mv...';END$$;
CREATE INDEX ix_abc_mv ON public.rental_by_category USING btree (category);
SET check_function_bodies = true;
