-- Script generated by Redgate Compare v1.11.2.9453

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.ix_abc_mv';END$$;
DROP INDEX public.ix_abc_mv;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.rental_by_category';END$$;
DROP MATERIALIZED VIEW public.rental_by_category;
SET check_function_bodies = true;
