-- Script generated by Redgate Compare v1.11.2.9453

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.rental_by_category...';END$$;
CREATE MATERIALIZED VIEW public.rental_by_category (category, total_sales) AS SELECT c.name AS category,
    sum(p.amount) AS total_sales
   FROM (((((public.payment p
     JOIN public.rental r ON ((p.rental_id = r.rental_id)))
     JOIN public.inventory i ON ((r.inventory_id = i.inventory_id)))
     JOIN public.film f ON ((i.film_id = f.film_id)))
     JOIN public.film_category fc ON ((f.film_id = fc.film_id)))
     JOIN public.category c ON ((fc.category_id = c.category_id)))
  GROUP BY c.name
  ORDER BY (sum(p.amount)) DESC;;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.ix_abc_mv...';END$$;
CREATE INDEX ix_abc_mv ON public.rental_by_category USING btree (category);
SET check_function_bodies = true;
